### ISSUE TITLE
multicore-opam breaks ppx_tools for 4.02.3

### ISSUE THREAD

**Issue by gasche** [ocaml-multicore/multicore-opam#10]
On my machine (with the multicore-opam repo installed), running `opam install --switch=4.02.3 ppx_tools` runs into the following failure:

```
#=== ERROR while compiling ppx_tools.5.0+4.02.3 ===============================#
# context     2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.02.3 | git+https://github.com/ocamllabs/multicore-opam.git
# path        ~/.opam/4.02.3/.opam-switch/build/ppx_tools.5.0+4.02.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build make all
# exit-code   2
# env-file    ~/.opam/log/ppx_tools-17861-d2c37b.env
# output-file ~/.opam/log/ppx_tools-17861-d2c37b.out
### output ###
# ocamlc -bin-annot -w +A-4-17-44-45 -I +compiler-libs -safe-string -c ast_convenience.mli
# ocamlc -bin-annot -w +A-4-17-44-45 -I +compiler-libs -safe-string -c ast_convenience.ml
# ocamlc -bin-annot -w +A-4-17-44-45 -I +compiler-libs -safe-string -c ast_mapper_class.mli
# ocamlc -bin-annot -w +A-4-17-44-45 -I +compiler-libs -safe-string -c ast_mapper_class.ml
# File "ast_mapper_class.ml", line 337, characters 6-17:
# Error: This variant pattern is expected to have type Parsetree.pattern_desc
#        The constructor Ppat_effect does not belong to type Parsetree.pattern_desc
# make: *** [Makefile:69: ast_mapper_class.cmo] Error 2
```

After a fair bit of headscratching, I realized that `multicore-opam` exports a `ppx_tools.5.1+4.06.0+multicore-1` package, but also a `ppx_tools.5.0+4.02.3`. The latter seems to override the standard-depo-provided 4.02.3 version, which results in this failure.

**Comment by kayceesrk** [comment]
> I just tried to workaround this issue by setting the multicore repo to a lower priority, but it doesn't appear to fix the problem.

That is odd. I'll have a look at this issue.

**Comment by kayceesrk** [comment]
Unlikely to fix this issue. We now have a `no-effect-syntax` branch, that is useful if the aim is to use domain-only multicore: https://github.com/ocaml-multicore/ocaml-multicore#variants.

We should come back to this issue when the focus shifts to effect handlers.

**Comment by cdaringe** [comment]
Hey all, I just reached this issue trying to experiment with effects in a current codebase w/ ppx_tools.

```
$ opam install ppx_tools
...snip...
#=== ERROR while compiling ppx_tools.6.2 ======================================#
# context     2.0.7 | macos/x86_64 | ocaml-secondary-compiler.4.10.0 ocaml-variants.4.10.0+multicore | https://opam.ocaml.org#c06ea43f
...snip...
# Warning 8: this pattern-matching is not exhaustive.
# ...snip...
# File "410/ast_mapper_class.ml", lines 611-656, characters 2-3:
# Error: Some record fields are undefined: effect_constructor
```

Am I reading the above correctly that ppx_tools is not compat w/ multicore/effects?

**Comment by gasche** [comment]
Yes, afaik nobody has worked on adapting the PPX tools to the internal AST changes that come with the effect syntax. If you want to experiment with Multicore, the easiest approach is to use the `no-effect-syntax` branch proposed by @kayceesrk above. If you specifically want to experiment with effect handlers, then you may have to implement support in the ppx tooling yourself, as experimental pins. (Such a support would come handy when, in the future, we do move to upstream support for effect handlers, but there may have been various changes to the feature by then that may require a rework of the patches.)

**Comment by kayceesrk** [comment]
It may not be the appropriate time for ppx support for effect syntax. The effect syntax is still very experimental and may change in the near future. It may be wise to wait for a few months before working on this.
