### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by jteg68** [ocaml-multicore/multicore-opam#24]
Hi,

when following the instruction

opam update
opam switch create 4.10.0+multicore --packages=ocaml-variants.4.10.0+multicore,ocaml-secondary-compiler --repositories=multicore=git+https://github.com/ocamllabs/multicore-opam.git,default

but with added --debug-level=5

I get an error 
00:00.841  FILE(environment)      Read ~/.opam/4.10.0+flambda/.opam-switch/environment in 0.000s
00:00.850  PROC                   safe_unlink: /home/teg/.opam/log/command-ocamlc-14824-42bb52.info
00:00.851  PROC                   safe_unlink: /home/teg/.opam/log/command-ocamlc-14824-42bb52.env
00:00.851  PROC                   safe_unlink: /home/teg/.opam/log/command-ocamlc-14824-42bb52.out
00:00.851  GSTATE                 Failed to evaluate global variable sys-ocaml-version: "ocamlc": command not found.
[ERROR] ocaml-variants = 4.10.0+multicore no matching version
00:01.172  SYSTEM                 rm /home/teg/.opam/opam-init/variables.sh

#:~/.opam$ ocamlc --version
4.10.0

#:~/.opam$ opam --version
2.0.5

Any suggestion on how to continue looking for the error?

/Jörgen

**Comment by kayceesrk** [comment]
> [ERROR] ocaml-variants = 4.10.0+multicore no matching version

Is surprising to see. @dra27 any thoughts on what might be going wrong?

**Comment by dra27** [comment]
What happens if you do `opam update -a` first?

Just to confirm - you see the `[ERROR] ocaml-variants = 4.10.0+multicore no matching version` without `--debug-level=5`, right? The ocamlc not found has nothing to do with it, and is correct (assuming you haven't installed ocaml with your *system* package manager?). The `ocamlc --version` you're running afterwards is almost certainly `/home/teg/.opam/4.10.0+flambda/bin/ocamlc`, if you check with `which ocamlc`.

**Comment by jteg68** [comment]
Thanks.

After `opam upgrade -a && opam update` the installation starts, but does not complete.
There are a few log files created and one of them is maybe interesting as it points to an error in the c code. See the attached file.
I can attach more files if needed.

/Jörgen
[ocaml-variants-18124-ebe0e0.out.txt](https://github.com/ocaml-multicore/multicore-opam/files/4987591/ocaml-variants-18124-ebe0e0.out.txt)

**Comment by dra27** [comment]
Ok, what happened before is that you dutifully followed the instructions with a previous version of multicore - the `—repos` switch doesn’t update the repo (I think this is arguably poor behaviour of `opam` in this case) so you didn’t have the new package.

The next bit does look like an actual bug, yes!

**Comment by jteg68** [comment]
OK. Let me know if there is something I can do to help out, like testing of some changes.

**Comment by jteg68** [comment]
I have now tried installation with a freshly created user. The installation starts but fails after some time. The console output is included below. Do you have any suggestions? If not, I can try again at some later time.
/Jörgen

```
tst@zbox:~$ opam switch create 4.10.0+multicore --packages=ocaml-variants.4.10.0+multicore,ocaml-secondary-compiler --repositories=multicore=git+https://github.com/ocamllabs/multicore-opam.git,default
Creating repository multicore...
[multicore] Initialised

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-secondary-compiler.4.10.0] found in cache
[ocaml-variants.4.10.0+multicore] downloaded from https://github.com/ocamllabs/ocaml-multicore/archive/parallel_minor_gc.tar.gz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
â installed base-bigarray.base
â installed base-threads.base
â installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at "/home/tst/.opam/opam-init/hooks/sandbox.sh build make -j3 world".
â installed ocaml-secondary-compiler.4.10.0

#=== ERROR while compiling ocaml-variants.4.10.0+multicore ====================#
# context     2.0.5 | linux/x86_32 |  | git+https://github.com/ocamllabs/multicore-opam.git
# path        ~/.opam/4.10.0+multicore/.opam-switch/build/ocaml-variants.4.10.0+multicore
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j3 world
# exit-code   2
# env-file    ~/.opam/log/ocaml-variants-30366-562576.env
# output-file ~/.opam/log/ocaml-variants-30366-562576.out
### output ###
# caml/misc.h:153:36: note: in expansion of macro âCAML_STATIC_ASSERT_3â
# [...]
#       |                                    ^~~~~~~~~~~~~~~~~~~~
# caml/misc.h:154:31: note: in expansion of macro âCAML_STATIC_ASSERT_2â
#   154 | #define CAML_STATIC_ASSERT(b) CAML_STATIC_ASSERT_2(b, __LINE__)
#       |                               ^~~~~~~~~~~~~~~~~~~~
# caml/domain_state.h:60:1: note: in expansion of macro âCAML_STATIC_ASSERTâ
#    60 | CAML_STATIC_ASSERT(
#       | ^~~~~~~~~~~~~~~~~~
# make[1]: *** [Makefile:343: minor_gc_b.o] Error 1
# make[1]: *** [Makefile:343: major_gc_b.o] Error 1
# make[1]: Leaving directory '/home/tst/.opam/4.10.0+multicore/.opam-switch/build/ocaml-variants.4.10.0+multicore/runtime'
# make: *** [Makefile:348: coldstart] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
ââ The following actions failed
â Î» build ocaml-variants 4.10.0+multicore
ââ
ââ The following changes have been performed (the rest was aborted)
â â install base-bigarray            base
â â install base-threads             base
â â install base-unix                base
â â install ocaml-secondary-compiler 4.10.0
ââ
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] n

```

**Comment by shakthimaan** [comment]
Can you please let us know which OS you are using?

**Comment by jteg68** [comment]
Certainly!

```
teg@zbox:~$` lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	unstable
Codename:	sid

teg@zbox:~$ uname -a
Linux zbox 4.9.0-9-686-pae #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) i686 GNU/Linux

teg@zbox:~$ cat /proc/sys/kernel/tainted 
0
```

One extra piece of information that is not obvious from the above: it's a 32-bit system.

**Comment by dra27** [comment]
@jteg68 - Multicore OCaml only supports x86_64 systems at the moment. Sorry, I should have spotted that in your original build log!

**Comment by jteg68** [comment]
Good, then we know it's not a real bug. Please close this report.
If you need testing help once you aim for 32, let me know.

**Comment by cdaringe** [comment]
> Multicore OCaml only supports x86_64

what luck that i just stumbled across this. i was going to lengths to try out effects for an ARM 7 32bit build! :)

**Comment by jteg68** [comment]
dra27,

sorry for a late reply.
Why stay on 32-bit system? No reason really, but I use the computer I have at the moment and it's good enough. I prefer low end computers that don't need a lot of noisy fans, so it can be used in the living room with the kids watching cartoons while I have an emacs open beside the youtube window.
This is all for my private explorations, there is no reason to stray from your x86_64 track.

**Comment by avsm** [comment]
We've brought up the question of 32-bit support in the core OCaml dev meeting, so there'll be a decision ahead of the 5.0 release about what to do about that. Thanks for the report!

**Comment by jteg68** [comment]
Thanks.
I'm now using the 64 bit version.

/Jörgen
