### ISSUE TITLE
Remove secondary compiler

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/multicore-opam#36]
Now that systhreads have been merged into Multicore OCaml, we should no longer need the secondary compiler. We should test and update the instructions appropriately.

**Comment by rgrmrts** [comment]
👋 I'm newly watching the whole Multicore OCaml story and eager to contribute if I can.

Would the following be sufficient:

1. Install Multicore OCaml with
```
$ opam switch create 4.10.0+multicore --packages=ocaml-variants.4.10.0+multicore --repositories=multicore=git+https://github.com/ocamllabs/multicore-opam.git,default
$ opam switch 4.10.0+multicore
$ opam install dune domainslib
```

2. Update the documentation on https://github.com/ocaml-multicore/domainslib and https://github.com/ocaml-multicore/multicore-opam to reflect the updated install instructions above (removes the `ocaml-secondary-compiler` package)

3. Run the tests in the `domainslib` repository

If the above sounds good, I'd be happy to take this on!

**Comment by kayceesrk** [comment]
Hi @rgrmrts, Apologies for looking at this only now. 

The steps look great. It would be great if you could reply with your interest in doing this in the next few days. I can help with any issues in this thread.

**Comment by rgrmrts** [comment]
Thanks for the reply. Yeah, I'm happy to tackle this in the next few days.

**Comment by kayceesrk** [comment]
Apologies. It looks like @shakthimaan already has a PR open. You can contribute by reviewing the PR and participating in the discussion.

**Comment by avsm** [comment]
the secondary compiler is now long gone :)
