### ISSUE TITLE
multicore merlin

### ISSUE THREAD

**Issue by mattpallissard** [ocaml-multicore/multicore-opam#39]
I have a fork of this repo with merlin and dot-merlin-reader. I've patched them to work with the 4.10 multicore fork. I based it off of HEAD so they have a few extra commits. Meaning, they don't technically match the current merlin release, 3.4.1.

I've bumped a long standing issue in the merlin repo to see if they'll house a branch that can track the multicore fork. Until I can get matched back up with a proper release number, would you accept a PR that is few patches ahead of the current merlin release?

https://github.com/mattpallissard/multicore-opam/tree/dev/multicore_410
https://github.com/mattpallissard/merlin
ocaml/merlin#823

Thanks in advance.

**Comment by kayceesrk** [comment]
Thanks @mattpallissard. This is a valuable contribution. I haven't looked at the details of https://github.com/ocaml/merlin/issues/1197, but from your message it might be the case that a merlin branch to track multicore is tricky. Correct me if I am wrong. 

If you can make a PR to this repo with your changes that point to your own repo, for now, it would already be useful.

**Comment by kayceesrk** [comment]
I don't use merlin, but if someone who uses merlin can try it out, it would be quite useful feedback. @shakthimaan @Sudha247 @Engil?

**Comment by mattpallissard** [comment]
@kayceesrk you're correct.  Up until recently merlin had support for multiple ocaml versions.  This made it easy to wire up a multi-core version that was detected at compile time.  However, going forward they decided to only support the latest version of ocaml.  As far as I can tell this makes implementing multi-core upstream impossible until it's merged into mainline.

PR opened, #40

**Comment by Sudha247** [comment]
Thank you for your efforts @mattpallissard! I tried your merlin multicore branch on VSCode and Atom, and it works great. 

![image](https://user-images.githubusercontent.com/13328130/100968529-7ff32480-3557-11eb-83d4-6389f51780cb.png)

When I was using it with ocaml-lsp-server, the server crashed many times and stopped working on my multicore switch after a point. This probably has something to do with the lsp-server itself and not merlin.

I also see that effect syntax is not recognized by merlin, is this expected?
![image](https://user-images.githubusercontent.com/13328130/100969815-b92c9400-3559-11eb-969c-c3a87adb4708.png)

**Comment by mattpallissard** [comment]
@Sudha247 I'm curious as to why it'd be crashing.  If you could come up with a reproduce able case I'd dig into it.

As for the effect syntax, I overlooked that let me look into fixing that and get back to you.

**Comment by EduardoRFS** [comment]
ocaml-lsp crashes even when using the `no-effect-system` branch with merlin, will try to debug it

**Comment by EduardoRFS** [comment]
My workaround

https://github.com/EduardoRFS/ocaml-lsp/commit/31a7b708f384458c807105e244557688c228d830

**Comment by mattpallissard** [comment]
I've gone and added the effect syntax. I force-pushed so the git history was clean.

I haven't got around to testing it more than the output below.  I also haven't tried to use ocmal-lsp-server with the patched dot-merlin-reader yet.  I'll try to get around to that in the next day or two.
```
opam repo add matt-multicore "git+https://github.com/mattpallissard/multicore-opam.git#dev/multicore_410"
opam install dot-merlin-reader=3.4.1
```
```
~  cat test.ml
effect Conversion_failure : string -> int
```

```
~  ocamlmerlin single errors -filename test.ml < test.ml | jq
{
  "class": "return",
  "value": [],
  "notifications": [],
  "timing": {
    "clock": 6,
    "cpu": 4,
    "query": 0,
    "pp": 0,
    "reader": 1,
    "ppx": 0,
    "typer": 3,
    "error": 0
  }
}
```
```
~  echo $(ocamlmerlin single dump -what parsetree -filename test.ml < test.ml | jq '.["value"]')

"[
 structure_item (test.ml[1,0+0]..[1,0+41])
 Pstr_effect
 effect_constructor (test.ml[1,0+7]..[1,0+41])
 peff_name = \"Conversion_failure\"
 peff_kind =
 Peff_decl
 [
 core_type (test.ml[1,0+28]..[1,0+34])
 Ptyp_constr \"string\" (test.ml[1,0+28]..[1,0+34])
 []
 ]
 core_type (test.ml[1,0+38]..[1,0+41])
 Ptyp_constr \"int\" (test.ml[1,0+38]..[1,0+41])
 []
]
```

**Comment by Sudha247** [comment]
Thanks @EduardoRFS and @mattpallissard! https://github.com/ocaml-multicore/ocaml-multicore/pull/458 removes effect syntax from typed tree. I tested @mattpallissard's latest patch of merlin on top of that branch, ocaml-lsp seems not to crash anymore.

**Comment by mattpallissard** [comment]
I patched ocaml-lsp-server to work with this version of merlin and verified that dot-merlin-reader works inas expected with the ocaml-multicore/ocaml-multicore:parallel_minor_gc branch. attached is my vim output using ocaml-lsp-server.

```
~  opam repo add matt-multicore "git+https://github.com/mattpallissard/multicore-opam.git#dev/multicore_410"
~  opam install dot-merlin-reader=3.4.1
~  opam pin add ocaml-lsp-server https://github.com/mattpallissard/ocaml-lsp.git
```

![image](https://user-images.githubusercontent.com/24529534/102384256-5982af80-3f81-11eb-814b-d853a0616374.png)

**Comment by Sudha247** [comment]
Thank you @mattpallissard! I can confirm that the patched `ocaml-lsp` works fine on both `parallel_minor_gc` and `no-effect-syntax`. Could you please add this `ocaml-lsp` patch to #40? It will be very useful.

**Comment by EduardoRFS** [comment]
I tried it and it works partially on the `no-effect-syntax`, on a Reason project that I've it keeps crashing, but with `.ml` files it works, maybe something related to ppx?

**Comment by mattpallissard** [comment]
@Sudha247 I updated the PR, adding ocaml-lsp-server to it. I required the 3.4.1 version of merlin-dot-reader, which is included in the PR.
```
opam repo add matt-multicore "git+https://github.com/mattpallissard/multicore-opam.git#dev/multicore_410"
opam install ocaml-lsp-server
```

@EduardoRFS , I wound up rebasing off up upstream ocaml-lsp so there are quite a few changes.  If it still doesn't work after re-installing can you provide a minimal reproduce able example?

**Comment by EduardoRFS** [comment]
@mattpallissard just create a executable using `.re`(on dune you just need to install @opam/reason) write 

```reason
open String;
let get = get;
```

And hover anything, your LSP will crash when using the `no-effect-syntax`

**Comment by mattpallissard** [comment]
@EduardoRFS I don't plan on spending time debugging reason.   I did do a quick test and was unable to reproduce your issue.  Please make sure that you're using the correct versions from the multicore repo I posted above.


![one](https://user-images.githubusercontent.com/24529534/103673827-e55d7b00-4f32-11eb-816e-e3f6c3a2e3eb.jpg)
![two](https://user-images.githubusercontent.com/24529534/103673833-e5f61180-4f32-11eb-8180-d8cfae5e764a.jpg)
![three](https://user-images.githubusercontent.com/24529534/103673830-e5f61180-4f32-11eb-81c3-a5ffdbf1652a.jpg)
![four](https://user-images.githubusercontent.com/24529534/103673822-e4c4e480-4f32-11eb-8ad9-4cc527ef443c.jpg)

**Comment by Sudha247** [comment]
Merlin with multicore support has been added in #40. Closing this issue.

@EduardoRFS mentioned in a private thread that merlin and ocaml-lsp work with Reason now. If there are any other issues on Reason please feel free to open a new one.
