### ISSUE TITLE
Merlin eats all the memory

### ISSUE THREAD

**Issue by paracetamolo** [ocaml-multicore/multicore-opam#58]
Using `ocaml-variants.4.12.0+domains` and merlin 4.2-412, after a few seconds of editing in Emacs, Merlin eats all the ram and gets killed by the OS.

**Comment by kayceesrk** [comment]
@Engil do you use merlin and can have a look at this? I wonder if this is related to the fix that we put in https://github.com/ocaml-multicore/ocaml-multicore/pull/628.

**Comment by Engil** [comment]
Hello,
I just checked, before #628 Merlin was also a victim of this behavior.
I checked against our latest changes, it seems the problem went away with #628.
@paracetamolo can you update your installation and check is the problem persists for you?

**Comment by paracetamolo** [comment]
It seems to be working fine now. Thanks for the quick fix.
